# Generated by Django 5.0.7 on 2024-07-23 09:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cards.basemodel')),
            ],
            bases=('cards.basemodel',),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cards.basemodel')),
                ('front', models.TextField()),
                ('back', models.TextField()),
                ('card_deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.deck')),
            ],
            bases=('cards.basemodel',),
        ),
    ]
